name: Docker
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Log into registry
        run: |
          echo "${{ secrets.DOCKER_PASSWD }}" | docker login -u jonathan52306 --password-stdin
          echo "${{ secrets.DOCKER_PASSWD }}" | docker login  ${{ secrets.REGISTRY_HCAAS }} --username jonathan --password-stdin
          echo "${{ secrets.DOCKER_PASSWD }}" | docker login  ${{ secrets.REGISTRY_ALIYUN }} --username jonathon53456 --password-stdin
      - name: Build and push image
        run: |
          docker build -t jonathan52306/docker_beginner:latest -f Dockerfile .
          docker tag jonathan52306/docker_beginner:latest ${{ secrets.REPO_HCAAS }}/docker_beginner:latest
          docker tag jonathan52306/docker_beginner:latest ${{ secrets.REPO_ALIYUN }}/docker_beginner:latest
          docker push jonathan52306/docker_beginner:latest
          docker push ${{ secrets.REPO_HCAAS }}/docker_beginner:latest
          docker push ${{ secrets.REPO_ALIYUN }}/docker_beginner:latest

