name: Docker
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Log into registry
        run: |
          echo "${{ secrets.DOCKER_PASSWD }}" | docker login -u jonathan52306 --password-stdin
      - name: Build and push image
        run: |
          docker build -t jonathan52306/docker_beginner:mc -f Dockerfile-Minecraft.dockerfile .
          docker push jonathan52306/docker_beginner:mc