name: Docker-youtube-dl_1drv
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Log into registry
        run: |
          echo "${{ secrets.DOCKER_PASSWD }}" | docker login -u jonathan52306 --password-stdin
      - name: Build and push image
        run: |
          docker build -t jonathan52306/docker_beginner:ytp-dl -f Dockerfile-youtube-dl_1drv.dockerfile .
          docker push jonathan52306/docker_beginner:ytb-dl